name: Android CI (APK)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-35
            build-tools;35.0.0
            platform-tools
            tools

      # 👇 Add this step
      - name: Accept Android SDK licenses (non-interactive)
        run: yes | sdkmanager --licenses
        shell: bash

      - name: Build debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrownLogic-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
